language: go

env:
  - CGO_ENABLED=0 FSECURE_VERSION="11.10.68" FSECURE_ADDRESS="/tmp/.fsav-0"

before_install:
  - sudo rm -vf /opt/jdk_switcher/jdk_switcher.sh
  - sudo dpkg --print-foreign-architectures
  - sudo dpkg --add-architecture i386
  - sudo dpkg --print-foreign-architectures
  - sudo apt-get update -qq
  - sudo apt-get install libc6-dev:i386 libpam-modules:i386 libstdc++6:i386 rpm zlib1g:i386
  - curl -Ov https://download.f-secure.com/corpro/ls/ls11.10/fsls-${FSECURE_VERSION}-rtm.tar.gz
  - tar xzvf fsls-${FSECURE_VERSION}-rtm.tar.gz
  - sudo chmod +x ${TRAVIS_BUILD_DIR}/fsls-${FSECURE_VERSION}-rtm/fsls-${FSECURE_VERSION}
  - sudo ${TRAVIS_BUILD_DIR}/fsls-${FSECURE_VERSION}-rtm/fsls-${FSECURE_VERSION} --command-line-only --auto standalone lang=en noremotewui nolocallogin nofirewall
  - sudo ./configure-fsav.sh
  - sudo mkdir -p /var/spool/testfiles
  - sudo cp -v examples/data/* /var/spool/testfiles/

go:
  - 1.x
  # - master

script:
  go test -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
